version: '3'

services:
    
  gazebo:
    build: 
      context: ./
      dockerfile: Dockerfile_gz
    #image: ubun-gaz
    tty: true
    healthcheck:
      test: "exit 0"
      interval: 15s
      timeout: 15s
      retries: 5
    ports:
      - "14580:14580/udp"
      - "18570:18570/udp"
    networks:
      data_network:
        aliases:
          - gazebo

  qgroundcontrol:
    build: 
      context: ./
      dockerfile: Dockerfile_qgc
    #image: ubuntu-qground
    ports:
      - "14540-14561:14540-14561/udp"
      - "4560:4560/tcp"
    depends_on:
      gazebo:
        condition: service_healthy
    networks:
      data_network:
        aliases:
          - qgroundcontrol
    environment:
      - DISPLAY=172.24.93.47:0.0
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN


networks:
    data_network:
      external: false